### PR TITLE
Create foreign table for fdw

### PR DESCRIPTION
**Pull request by mcproger**
Hi, thanks for your project.
This is a fix for a missing `CREATE FOREIGN TABLE` section

### CODE REVIEW

**Comment by ildus** [comment]
hi @mcproger , the `IMPORT FOREIGN SCHEMA` command should create the tables, have you looked what tables were created?

**Comment by mcproger** [comment]
@ildus 
In my case, `IMPORT FOREIGN SCHEMA` does not create a foreign table. I tested it twice and both ended up with manual `CREATE FOREIGN TABLE`. I use postgresql 12 and latest clickhouse-server

**Comment by ildus** [comment]
Have you done other steps on ClickHouse side? From start of Usage section.

**Comment by mcproger** [comment]
Yeah, sure. I created sample database and tables. And after manual creation of foreign tables, I can query data from clickhouse through fdw and it works well.

**Comment by ildus** [comment]
Yes, it should've been `IMPORT FOREIGN SCHEMA "test_database" FROM SERVER clickhouse_svr INTO public;`, I fixed the README. Thank you.

**Pull request closed without merging**
